[카일] OSIV
woowacourse/javable pull request #192
Opened 2020-09-10 15:34 UTC by KIMSIYOUNG

[여기](https://github.com/woowacourse/javable/blob/docs/osiv/_posts/2020-09-11-osiv.md)서 편하게 보세요!
closes #191

2020-09-14 11:40 UTC, lxxjn0 approved these changes
카일, 글 잘 읽었습니다.
어쩌다보니 제가 라테와 카일 글의 리뷰어이고, 어쩌다보니 라테 글에서 OSIV에 대해 언급했는데 딱 주제가 OSIV네요!!!
그래서 더 문맥이 잘 파악되고 재밌게 읽었던 것 같아요.
몇가지 부분에 대해서만 리뷰 남겨뒀으니 참고 부탁드릴게요 :)

2020-09-14 11:40 UTC, lxxjn0 commented on _posts/2020-09-11-osiv.md
> +그렇다면 이상한 점은 Controller 계층은 분명 트랜잭션과 영속성 컨텍스트가 닫혀있는 상황입니다. 이런 상황에서 ResponseDto에서 Post 엔티티를 초기화하고 있습니다. 왜 예외가 터지지 않았을까요?
이 부분에 많은 설명들이 축약되어 있는 것 같아요.

- 컨트롤러 계층은 트랜잭션과 영속성 컨텍스트가 닫혀있다.
- 영속성 컨텍스트가 닫혀있으면 지연 로딩된 객체를 초기화 할 수 없다.
- 그런데 MemberResponse.of 메서드는 컨트롤러에서 호출이 된다.
- 함수 내부에서는 getPost를 가져와서 PostResponse로 변환하는데 이 상황에서 왜 문제가 발생하지 않는 것일까?

이런 흐름으로 조금만 더 자세하게 적어주면 읽기 쉬울 것 같아요 :)

2020-09-14 11:40 UTC, lxxjn0 commented on _posts/2020-09-11-osiv.md
> +그렇다면 OSIV는 무엇일까요? 단어에서 유추할 수 있듯이 `View 단에서 Session(영속성 컨텍스트)가 열거냐` 라는 의미입니다. OSIV가 OFF 되어 있는 설정에서, 스프링에 기본으로 설정된 영속성 컨텍스트의 지속 기간은 Transaction의 범위와 동일합니다. 아래의 그림과 같이 트랜잭션이 시작되며 영속성 컨텍스트가 열리고 트랜잭션이 끝나는
```suggestion
그렇다면 OSIV는 무엇일까요? 단어에서 유추할 수 있듯이 `View 단에서 Session(영속성 컨텍스트)을 열거냐` 라는 의미입니다. OSIV가 OFF 되어 있는 설정에서, 스프링에 기본으로 설정된 영속성 컨텍스트의 지속 기간은 Transaction의 범위와 동일합니다. 아래의 그림과 같이 트랜잭션이 시작되며 영속성 컨텍스트가 열리고 트랜잭션이 끝나는 시점에 영속성 컨텍스트는 닫힙니다.
```

이렇게 수정하는게 더 자연스럽게 읽히는 것 같아요!

2020-09-14 11:40 UTC, lxxjn0 commented on _posts/2020-09-11-osiv.md
> +하지만 스프링 부트가 자동설정으로 OSIV를 TRUE로 변경하여 제공할 때 그림은 아래와 같습니다.  이 경우에도 트랜잭션은 Service 계층 이후에 사라집니다. 하지만 영속성 컨텍스트는 컨트롤러 계층까지 열려있음을 볼 수 있습니다. 이러한 옵션이 자동으로 적용되어 있기 때문에 Controller에서도 프록시 객체를 초기화 할 수 있었던 것입니다.
헉! 혹시 그렇다면 따로 어노테이션이나 설정파일을 설정하지 않아도 이러한 문제가 발생하지 않는 건가요???

2020-09-21 23:34 UTC, pobiconan requested changes
문서 작성하느라 수고했네요. 💯 
문서 전체적으로 통일성을 기하면 더 좋은 글이 될 것 같아요.

2020-09-21 23:34 UTC, pobiconan commented on _posts/2020-09-11-osiv.md
> +title: "OSIV"
OSIV를 full text를 제목으로 하는 것은 어떨까?

2020-09-21 23:34 UTC, pobiconan commented on _posts/2020-09-11-osiv.md
> +이번 포스팅은 Spring boot와 Jpa를 활용하여 개인 프로젝트를 개발 중 Jpa의 예상치 못한 동작을 발견하게 되어 이를 공유하고자 작성하였습니다. 읽고 계신 분들도 상황을 보며 어떤 점이 이상한 것인지 예상해 보시고 아래의 답을 보면 좋을 것 같습니다. 상황은 아래와 같습니다!
Spring boot와 Jpa를
=> Spring Boot와 JPA를

2020-09-21 23:34 UTC, pobiconan commented on _posts/2020-09-11-osiv.md
> +이번 포스팅은 Spring boot와 Jpa를 활용하여 개인 프로젝트를 개발 중 Jpa의 예상치 못한 동작을 발견하게 되어 이를 공유하고자 작성하였습니다. 읽고 계신 분들도 상황을 보며 어떤 점이 이상한 것인지 예상해 보시고 아래의 답을 보면 좋을 것 같습니다. 상황은 아래와 같습니다!
우리 문서 작성의 컨벤션은 높임말을 쓰지 않는 것으로 알고 있다.
내용 수정하는 것이 어떨까?

2020-09-21 23:34 UTC, pobiconan commented on _posts/2020-09-11-osiv.md
> +그렇다면 이상한 점은 Controller 계층은 분명 트랜잭션과 영속성 컨텍스트가 닫혀있는 상황입니다. 이런 상황에서 ResponseDto에서 Post 엔티티를 초기화하고 있습니다. 왜 예외가 터지지 않았을까요?
왜 예외가 터지지 않았을까요?
=> 왜 예외가 발생하지 않았을까요?

2020-09-21 23:34 UTC, pobiconan commented on _posts/2020-09-11-osiv.md
> +사실 위의 문제는 실제로 트랜잭션과 영속성 컨텍스트가 닫힌 상태이기 때문에 예외가 터지는 것이 맞습니다. 그런데도 예외가 발생하지 않는 이유는 스프링 부트에서 OSIV 라는 설정을 자동으로 true로 설정하기 때문입니다.
앞에서는 Spring Boot이고 이곳에서는 스프링 부트인가?
통일하면 좋겠다

2020-09-21 23:34 UTC, pobiconan commented on _posts/2020-09-11-osiv.md
> +하지만 스프링 부트가 자동설정으로 OSIV를 TRUE로 변경하여 제공할 때 그림은 아래와 같습니다.  이 경우에도 트랜잭션은 Service 계층 이후에 사라집니다. 하지만 영속성 컨텍스트는 컨트롤러 계층까지 열려있음을 볼 수 있습니다. 이러한 옵션이 자동으로 적용되어 있기 때문에 Controller에서도 프록시 객체를 초기화 할 수 있었던 것입니다.
앞에서는 true이고, 이곳은 TRUE이다.
문서 전체적으로 통일성을 기하는 것이 좋겠다

2020-09-30 01:26 UTC, KIMSIYOUNG commented on _posts/2020-09-11-osiv.md
> +그렇다면 이상한 점은 Controller 계층은 분명 트랜잭션과 영속성 컨텍스트가 닫혀있는 상황입니다. 이런 상황에서 ResponseDto에서 Post 엔티티를 초기화하고 있습니다. 왜 예외가 터지지 않았을까요?
감사합니다!

2020-09-30 01:26 UTC, KIMSIYOUNG commented on _posts/2020-09-11-osiv.md
> +그렇다면 OSIV는 무엇일까요? 단어에서 유추할 수 있듯이 `View 단에서 Session(영속성 컨텍스트)가 열거냐` 라는 의미입니다. OSIV가 OFF 되어 있는 설정에서, 스프링에 기본으로 설정된 영속성 컨텍스트의 지속 기간은 Transaction의 범위와 동일합니다. 아래의 그림과 같이 트랜잭션이 시작되며 영속성 컨텍스트가 열리고 트랜잭션이 끝나는
헉 오타가 있었네요 감사합니다!

2020-09-30 01:26 UTC, KIMSIYOUNG commented on _posts/2020-09-11-osiv.md
> +하지만 스프링 부트가 자동설정으로 OSIV를 TRUE로 변경하여 제공할 때 그림은 아래와 같습니다.  이 경우에도 트랜잭션은 Service 계층 이후에 사라집니다. 하지만 영속성 컨텍스트는 컨트롤러 계층까지 열려있음을 볼 수 있습니다. 이러한 옵션이 자동으로 적용되어 있기 때문에 Controller에서도 프록시 객체를 초기화 할 수 있었던 것입니다.
네 맞습니당! Spring boot를 사용중이라면 의식하지 않고 사용하셔도 됩니다!

2020-09-30 01:26 UTC, KIMSIYOUNG commented on _posts/2020-09-11-osiv.md
> +title: "OSIV"
full text가 Open Session In View를 말하시는게 맞나요?! 그렇게 수정하였습니다.

2020-09-30 01:27 UTC, KIMSIYOUNG commented on _posts/2020-09-11-osiv.md
> +이번 포스팅은 Spring boot와 Jpa를 활용하여 개인 프로젝트를 개발 중 Jpa의 예상치 못한 동작을 발견하게 되어 이를 공유하고자 작성하였습니다. 읽고 계신 분들도 상황을 보며 어떤 점이 이상한 것인지 예상해 보시고 아래의 답을 보면 좋을 것 같습니다. 상황은 아래와 같습니다!
수정하였습니다!

2020-09-30 01:27 UTC, KIMSIYOUNG commented on _posts/2020-09-11-osiv.md
> +이번 포스팅은 Spring boot와 Jpa를 활용하여 개인 프로젝트를 개발 중 Jpa의 예상치 못한 동작을 발견하게 되어 이를 공유하고자 작성하였습니다. 읽고 계신 분들도 상황을 보며 어떤 점이 이상한 것인지 예상해 보시고 아래의 답을 보면 좋을 것 같습니다. 상황은 아래와 같습니다!
수정하였습니다!

2020-09-30 01:27 UTC, KIMSIYOUNG commented on _posts/2020-09-11-osiv.md
> +그렇다면 이상한 점은 Controller 계층은 분명 트랜잭션과 영속성 컨텍스트가 닫혀있는 상황입니다. 이런 상황에서 ResponseDto에서 Post 엔티티를 초기화하고 있습니다. 왜 예외가 터지지 않았을까요?
수정하였습니다!

2020-09-30 01:27 UTC, KIMSIYOUNG commented on _posts/2020-09-11-osiv.md
> +사실 위의 문제는 실제로 트랜잭션과 영속성 컨텍스트가 닫힌 상태이기 때문에 예외가 터지는 것이 맞습니다. 그런데도 예외가 발생하지 않는 이유는 스프링 부트에서 OSIV 라는 설정을 자동으로 true로 설정하기 때문입니다.
수정하였습니다!

2020-09-30 01:27 UTC, KIMSIYOUNG commented on _posts/2020-09-11-osiv.md
> +하지만 스프링 부트가 자동설정으로 OSIV를 TRUE로 변경하여 제공할 때 그림은 아래와 같습니다.  이 경우에도 트랜잭션은 Service 계층 이후에 사라집니다. 하지만 영속성 컨텍스트는 컨트롤러 계층까지 열려있음을 볼 수 있습니다. 이러한 옵션이 자동으로 적용되어 있기 때문에 Controller에서도 프록시 객체를 초기화 할 수 있었던 것입니다.
수정하였습니다!

2020-10-05 00:57 UTC, pobiconan approved these changes
피드백까지 반영하느라 수고했어요. 💯

2020-10-05 01:09 UTC, KimSeongGyu1 reviewed
늦어서 죄송합니다.
몰랐던 좋은 정보를 알게되어서 정말 좋은 글이네요
미리 리뷰를 다 해주셔서 별로 리뷰할 것은 없지만 글의 전체적인 결이 약간 깨지는 것 같은 부분이 있어서 그 부분에만 리뷰 남겼어요

2020-10-05 01:09 UTC, KimSeongGyu1 commented on _posts/2020-09-11-osiv.md
> +위의 코드는 회원의 아이디로 회원을 찾는 요청 API인데, 혹시 어떤 점이 이상한지 찾으셨나요? 사실 위의 코드는 어떤 매직에 의해 동작하는 것이며, 그 매직이 없었다면 동작하지 않아야 할 코드이다.
존댓말과 반말을 섞어서 사용하는데 통일하면 좋을 것 같아요
존댓말의 사용빈도가 낮으니 존댓말을 바꾸는게 좋을 것 같아요

2020-10-05 01:09 UTC, KimSeongGyu1 commented on _posts/2020-09-11-osiv.md
> +그렇다면 Controller 계층은 아래와 같은 상황입니다.
여기 존댓말이랑

2020-10-05 01:09 UTC, KimSeongGyu1 commented on _posts/2020-09-11-osiv.md
> +사실 위의 문제는 실제로 트랜잭션과 영속성 컨텍스트가 닫힌 상태이기 때문에 예외가 터지는 것이 맞다. 그런데도 예외가 발생하지 않는 이유는 Spring boot에서 OSIV 라는 설정을 자동으로 true로 설정하기 때문입니다.
여기

2020-10-05 01:09 UTC, KimSeongGyu1 commented on _posts/2020-09-11-osiv.md
> +    -> [여기](https://kingbbode.tistory.com/27)
이 부분은 조금 애매한 것 같아요
존댓말 유지해도 괜찮아 보입니다

2020-10-06 00:49 UTC, KimSeongGyu1 approved these changes

2020-10-13 02:44 UTC, merged