[보스독] 인수테스트에서 테스트 격리하기
woowacourse/javable pull request #206
Opened 2020-09-20 15:01 UTC by yeonnseok

fixes #159 
리뷰부탁드립니다. 감사합니다!

2020-09-21 09:53 UTC, pci2676 requested changes
보스독 잘 읽었습니다.
리뷰 남겼습니다~

2020-09-21 23:46 UTC, pobiconan requested changes
인수테스트를 구현하면 항상 고민하게 되는 내용이네요. 💯 
피드백 남겼으니 반영 여부를 한번 고려해 보면 좋겠네요

2020-09-21 23:46 UTC, pobiconan commented on _posts/2020-09-15-test-isolation.md
> +앞에서 언급한 계층들은 JUnit과 Spring Boot가 제공하는 도구들을 잘 활용하면 테스트 격리를 크게 신경쓰지않고 개발할 수 있다. 하지만 인수테스트에서는 경우가 조금 다르다.
신경쓰지않고
=> 띄워쓰기 확인 좀

2020-09-21 23:46 UTC, pobiconan commented on _posts/2020-09-15-test-isolation.md
> +테스트 격리가 안되는 근본적인 원인은 각각의 테스트가 하나의 데이터베이스를 공유하기 때문인데, 이를 방지하기 위해서 JUnit 과 Spring Boot에는 격리를 지원하는 도구를 제공한다.
이후 글이 데이터베이스를 기반으로 하고 있다.
따라서 이 부분을 다음과 같이 수정하는 것은 어떨까?

`테스트 격리가 안되는 근본적인 원인은 각각의 테스트가 하나의 자원을 공유하기 때문인데, 이를 방지하기 위해서 JUnit 과 Spring Boot에는 격리를 지원하는 도구를 제공한다. 단, 이 글에서는 공유 자원의 대표 주자라 할 수 있는 데이터베이스를 기준으로 글을 작성한다.`와 같은 표현을 넣어주면 어떨까?

2020-09-21 23:46 UTC, pobiconan commented on _posts/2020-09-15-test-isolation.md
> +하지만, 인수테스트의 경우 @SpringBootTest 어노테이션에 port를 지정하여 서버를 띄우게되는 데 이때, Http 클라이언트와 서버는 각각 다른 스레드에서 실행된다. 따라서 아무리 테스트 코드에 @Transactional 어노테이션이 있다고 하더라도 호출되는 쪽은 다른 스레드에서 새로운 트랜잭션으로 커밋하기 때문에 롤백 전략이 무의미해지는 것이
Http -> HTTP

2020-09-21 23:46 UTC, pobiconan commented on _posts/2020-09-15-test-isolation.md
> +만약 도메인에 대한 지식이 없는 사람이 테스트를 작성한다면, 연관관계 맵핑으로 생성되는 엔티티를 추적하는 데 어려움이 있을 것이고 이는 곧 비용이 증가를 불러오게 된다.
엔티티를 추적하는 데 어려움이 있을 것이고 이는 곧 비용이 증가를 불러오게 된다.
=>  문장 어색함. 
`엔티티를 추적하기 어렵게 만들고 구현과 유지 비용이 증가할 것이다.`

2020-09-21 23:46 UTC, pobiconan commented on _posts/2020-09-15-test-isolation.md
> +truncate을 쿼리는 앞서 살펴본 delete로 테이블을 초기화하는 방법보다는 상당히 괜찮은 방법이다.  API 요청도 필요없고, delete를 하기 위해서 하나씩 select(조회)를 할 필요도 없다.
truncate을 쿼리는 => truncate 쿼리는

2020-09-21 23:46 UTC, pobiconan commented on _posts/2020-09-15-test-isolation.md
> +#### 2) EntityManager로 직접 truncate 쿼리 실행
이 해결책은 JPA를 사용할 때의 제한된 해결책이지 않을까?
JPA를 사용하지 않는 경우는 어떻게 할 것인가?
이에 대한 대안도 제시해 주는 것이 좋지 않을까?

2020-09-21 23:50 UTC, KIMSIYOUNG requested changes
안녕하세요 보스독!
좋은 소재로 깔끔하게 잘 써주셨네요.
간단한 리뷰와 궁금한 점 남겼어요.
확인 부탁드립니다~

2020-09-21 23:50 UTC, KIMSIYOUNG commented on _posts/2020-09-15-test-isolation.md
> +하지만 TDD로 개발하는 개발자들은 Mock 프레임워크를 사용해서 테스트를 작성할 수 있는데, 이 방식이 효과적인 이유는 실제 데이터베이스를 건드리지도 않을 뿐만아니라, 계층 구조에서 단위테스트를 할 수 있다는 장점이 있기 때문이다.
레이어를 격리한 테스트와 TDD와 관련성이 있을까요? `하지만 TDD로 개발하는 개발자들은 Mock 프레임워크를 사용해서 테스트를 작성할 수 있는데` 이 부분이 조금 어색한 것 같아요!

2020-09-21 23:50 UTC, KIMSIYOUNG commented on _posts/2020-09-15-test-isolation.md
> +앞에서 언급한 계층들은 JUnit과 Spring Boot가 제공하는 도구들을 잘 활용하면 테스트 격리를 크게 신경쓰지않고 개발할 수 있다. 하지만 인수테스트에서는 경우가 조금 다르다.
격리를 통한 간단한 예제 하나정도 보여주는 것도 좋을 것 같습니다!

2020-09-21 23:50 UTC, KIMSIYOUNG commented on _posts/2020-09-15-test-isolation.md
> +하지만, 인수테스트의 경우 @SpringBootTest 어노테이션에 port를 지정하여 서버를 띄우게되는 데 이때, Http 클라이언트와 서버는 각각 다른 스레드에서 실행된다. 따라서 아무리 테스트 코드에 @Transactional 어노테이션이 있다고 하더라도 호출되는 쪽은 다른 스레드에서 새로운 트랜잭션으로 커밋하기 때문에 롤백 전략이 무의미해지는 것이
개인적으로 조금 추가 설명해주실 수 있나요? 잘 몰랐던 내용이라 이해가 잘 안되네요ㅜㅜ

2020-09-21 23:50 UTC, KIMSIYOUNG commented on _posts/2020-09-15-test-isolation.md
> +<img src="https://user-images.githubusercontent.com/42382027/93715349-b00b6800-fba3-11ea-8af9-e060e02a9208.png" width="780">
각 코드에 주석으로 간단하게 설명을 추가해주는 것은 어떨까요?
저의 경우는 start with 1 이 없어서 아이디로 확인할 때 예외를 많이 만났었는데, 이런 부분도 간략하게 언급해주는 것도 좋을거 같아용!

2020-09-21 23:50 UTC, KIMSIYOUNG commented on _posts/2020-09-15-test-isolation.md
> +> 여기서 비결정적 테스트란 같은 입력값에 대해 항상 같은 결과를 출력하지 않는 테스트를 말한다.
자동화된 테스트라는 것과는 다른 의미일까요?

2020-09-22 13:42 UTC, yeonnseok commented on _posts/2020-09-15-test-isolation.md
> +테스트 격리가 안되는 근본적인 원인은 각각의 테스트가 하나의 데이터베이스를 공유하기 때문인데, 이를 방지하기 위해서 JUnit 과 Spring Boot에는 격리를 지원하는 도구를 제공한다.
좀 더 매끄러운 표현이군요! 반영했습니다!

2020-09-22 15:05 UTC, yeonnseok commented on _posts/2020-09-15-test-isolation.md
> +앞에서 언급한 계층들은 JUnit과 Spring Boot가 제공하는 도구들을 잘 활용하면 테스트 격리를 크게 신경쓰지않고 개발할 수 있다. 하지만 인수테스트에서는 경우가 조금 다르다.
전체적으로 띄워쓰기를 점검하여 반영하였습니다!

2020-09-22 15:07 UTC, yeonnseok commented on _posts/2020-09-15-test-isolation.md
> +만약 도메인에 대한 지식이 없는 사람이 테스트를 작성한다면, 연관관계 맵핑으로 생성되는 엔티티를 추적하는 데 어려움이 있을 것이고 이는 곧 비용이 증가를 불러오게 된다.
감사합니다!

2020-09-22 15:09 UTC, yeonnseok commented on _posts/2020-09-15-test-isolation.md
> +#### 2) EntityManager로 직접 truncate 쿼리 실행
JPA에서 제공하는 EntityManager가 핵심적으로 table을 이름을 조사하고 truncate쿼리를 실행하는 역할을 합니다.
어떤 기술을 사용하더라도 table이름을 알아낼 수 있으면, 비슷한 방식으로 격리 방식을 사용할 수 있을 것으로 생각합니다.

따라서 이에 대한 부연설명을 추가해보았습니다.!!

2020-09-22 15:11 UTC, yeonnseok commented on _posts/2020-09-15-test-isolation.md
> +> 여기서 비결정적 테스트란 같은 입력값에 대해 항상 같은 결과를 출력하지 않는 테스트를 말한다.
제가 이해하는 바론 자동화된 테스트란 CI빌드 툴 등을 이용해서 빌드시에 자동으로 테스트를 하는 것으로 알고 있습니다.
또한 이글에서 말하고자하는 결정적 테스트란, 테스트 코드 자체에 대해서 반복적으로 수행되거나, 순서에 상관없이 수행되어도 항상 같은 결과(초록불)를 낼 수 있는 테스트를 의미합니다.

2020-09-22 15:15 UTC, yeonnseok commented on _posts/2020-09-15-test-isolation.md
> +하지만, 인수테스트의 경우 @SpringBootTest 어노테이션에 port를 지정하여 서버를 띄우게되는 데 이때, Http 클라이언트와 서버는 각각 다른 스레드에서 실행된다. 따라서 아무리 테스트 코드에 @Transactional 어노테이션이 있다고 하더라도 호출되는 쪽은 다른 스레드에서 새로운 트랜잭션으로 커밋하기 때문에 롤백 전략이 무의미해지는 것이
우리가 평소 작성했던 코드를 예시로 든다면, 인수테스트에서 서버를 띄워서 테스트를 하게 되었을때, RestAssured를 사용해서 HTTP요청을 보내는 클라이언트와 요청을 받고 로직을 수행하는 서버가 서로 다른 스레드에서 실행된다고합니다.
그렇게되면 서버의 트랜잭션은 테스트 영역에 영향을 받지않고 실제 서버처럼 커밋이 되기 때문에 테스트 코드에서 @Transactional 어노테이션을 사용한 롤백전략이 무의미하다는 것을 의미하고 있습니다! 

오늘 테코톡에서도 언급드릴 예정이니 참고해주시면 좋을 것 같습니다!

2020-09-22 15:39 UTC, yeonnseok commented on _posts/2020-09-15-test-isolation.md
> +<img src="https://user-images.githubusercontent.com/42382027/93715349-b00b6800-fba3-11ea-8af9-e060e02a9208.png" width="780">
주석을 달아보았습니다!

2020-09-22 15:40 UTC, yeonnseok commented on _posts/2020-09-15-test-isolation.md
> +하지만 TDD로 개발하는 개발자들은 Mock 프레임워크를 사용해서 테스트를 작성할 수 있는데, 이 방식이 효과적인 이유는 실제 데이터베이스를 건드리지도 않을 뿐만아니라, 계층 구조에서 단위테스트를 할 수 있다는 장점이 있기 때문이다.
이 부분에 설명이 조금 생략되어있긴한데 글 전체적으로 중요한 부분이 아니라서 약간의 보충 설명을 추가해보았습니다.

2020-09-23 08:39 UTC, pci2676 approved these changes

2020-09-26 06:11 UTC, KIMSIYOUNG approved these changes
개인적으로 조금 어려운 주제라 생각해서 여러가지를 많이 여쭤봤네요!
좋은 글 잘 읽었습니다. 고생하셨어요!

2020-10-05 01:01 UTC, pobiconan approved these changes
어려운 주제 다루느라 수고했어요. 💯

2020-10-05 01:01 UTC, merged