[비밥] Spring Boot 에서 properties 값 주입받기
woowacourse/javable pull request #218
Opened 2020-09-29 18:52 UTC by pci2676

[글](https://github.com/woowacourse/javable/blob/doc%2Fspring-properties-binding/_posts/2020-09-29-spring-properties-binding.md)

close #216

2020-10-03 06:48 UTC, DunDung approved these changes
고생하셨습니다 비밥 👍 
깔끔하게 정리되어있는 글이네요!
간단한 리뷰 남겼습니다!

2020-10-03 06:48 UTC, DunDung commented on _posts/2020-09-29-spring-properties-binding.md
> +대신 아래와 같이 PropertiesConfiguration 클래스에 **`@EnableConfigurationProperti`을 이용해서 생성할 Properties 클래스의 클래스 타입을 명시**해주면 됩니다.
```suggestion
대신 아래와 같이 PropertiesConfiguration 클래스에 **`@EnableConfigurationProperties`을 이용해서 생성할 Properties 클래스의 클래스 타입을 명시**해주면 됩니다.
```

2020-10-03 06:48 UTC, DunDung commented on _posts/2020-09-29-spring-properties-binding.md
> +가급적이면 `@ConfigurationProperties`을 사용하는 것이 좋아 보이지만 Spring Batch를 사용하면 `@Value`를 사용해야 하는 경우도 발생합니다. 따라서 언제나 그렇듯 **상황에 따라 알맞게 적절한 어노테이션을 선택해서 사용**해야 합니다.
Spring Batch를 사용하면 `@Value`를 사용해야 하는 경우가 어떤 건지 간단하게 언급해주는 게 좋지 않을까요??!

2020-10-14 12:30 UTC, yeonnseok requested changes
비밥! 좋은 글 써주시느라 고생많으셨습니다 ㅎㅎ (리뷰가 늦어 죄송해요)
우선 내용 구성은 너무나도 좋은 것 같습니다. 
다만 글이 경어체와 평어체가 중간중간 섞여있는 것 같아서 하나로 통일하는게 어떨지 싶습니다! (javable 다른 글들과 통일성을 위해서 평어체가 낫겠죠..?)
이 외에 몇가지 간단한 피드백 남겼어요! 확인하시고 반영해주시면 좋을 것 같습니다 ㅎㅎ

2020-10-14 12:30 UTC, yeonnseok commented on _posts/2020-09-29-spring-properties-binding.md
> +@ConfigurationProperties("constructor")
이 부분에서 properties의 최상위 value 이름이 계속 변해서 살짝 헷갈릴 소지가 있을 것 같습니다!
위에서 부터 하나로 통일하는게 어떨까요?

2020-10-14 12:30 UTC, yeonnseok commented on _posts/2020-09-29-spring-properties-binding.md
> +*final 필드를 명시하지 않는다면 setter가 없다는 exception이 발생합니다.*
final 필드가 없는 상황인데, setter가 없다는 예외가 발생한다는게 조금 이해가 안되는 것 같습니다. 스프링만 사용하는 setter api가 따로 존재하는건가요? 예외 내용이나 혹은 부연설명이 있으면 좋을 것 같습니다! ㅠ

2020-10-14 12:30 UTC, yeonnseok commented on _posts/2020-09-29-spring-properties-binding.md
> +*final 필드를 명시하지 않는다면 setter가 없다는 exception이 발생합니다.*
또한 final 필드보단 final 키워드라고 단어를 변경하는게 어떨까요?

2020-10-14 12:30 UTC, yeonnseok commented on _posts/2020-09-29-spring-properties-binding.md
> +    private Integer apiKey;
필드마다 한 줄 씩 띄우는건 어떨까요? 개인차가 있겠지만, 저는 한눈에 들어오지 않는 것 같아서 한번 제안드려봅니다!

2020-10-14 12:30 UTC, yeonnseok commented on _posts/2020-09-29-spring-properties-binding.md
> +
위 내용을 따라 읽어 내려오면, @ConfigurationProperties와 @ContructorBinding 어노테이션을 함께 썼을 때 비로소 앞서 언급한 문제들(타입안정성, 불변성)을 피할 수 있는 것 같아보입니다.
@constructorBinding 어노테이션도 비중있게 다루셨기 때문에 결론 부분에 언급이 들어가는게 어떨까요?

2020-10-15 06:40 UTC, pci2676 commented on _posts/2020-09-29-spring-properties-binding.md
> +*final 필드를 명시하지 않는다면 setter가 없다는 exception이 발생합니다.*
아 이부분 설명이 조금 모자라네요! 고마워요 추가하도록 할게요!

2020-10-15 06:40 UTC, pci2676 commented on _posts/2020-09-29-spring-properties-binding.md
> +@ConfigurationProperties("constructor")
테스트할때 하나의 프로젝트에서 진행하느라 계속 다르게 했었는데 글에서는 통일하는게 좋겠네요!

2020-10-15 09:01 UTC, pci2676 commented on _posts/2020-09-29-spring-properties-binding.md
> +
같이 언급하는 방향으로 수정했습니다~

2020-10-15 09:02 UTC, pci2676 commented on _posts/2020-09-29-spring-properties-binding.md
> +    private Integer apiKey;
그렇군요! 한칸씩 띄워놨습니다!

2020-10-15 09:02 UTC, pci2676 commented
@yeonnseok 
리뷰해주신 부분 반영했습니다. 
확인부탁드릴게요~

2020-10-15 12:56 UTC, yeonnseok approved these changes
반영이 빠르시군요! 확인했습니다!!

2020-10-16 00:56 UTC, pobiconan approved these changes
설정 파일 관련해 장/단점 구분해서 잘 정리했네요. 💯

2020-10-16 00:56 UTC, merged