[둔덩] Collection.forEach와 Stream.forEach는 뭐가 다를까?
woowacourse/javable pull request #223
Opened 2020-09-30 11:43 UTC by DunDung

초안입니다!!

fixes #222

2020-10-01 14:42 UTC, pci2676 requested changes

2020-10-01 14:42 UTC, pci2676 commented on _posts/2020-09-30-collection-stream-for-each.md
> +      nums.stream().forEach(System.out::println);
```suggestion
    nums.forEach(System.out::println);
    nums.stream().forEach(System.out::println);
```

2020-10-01 14:42 UTC, pci2676 commented on _posts/2020-09-30-collection-stream-for-each.md
> +      nums.stream().forEach(System.out::println);
```suggestion
    nums.forEach(System.out::println);
    nums.stream().forEach(System.out::println);
```

2020-10-01 14:42 UTC, pci2676 commented on _posts/2020-09-30-collection-stream-for-each.md
> +Collection.forEach는 따로 객체를 생성하지 않고 forEach 메서드를 호출한다. forEach 메서드는 Iterable 인터페이스의 default 메서드인데, Collection 인터페이스에서 Iterable 인터페이스를 상속하고 있기에 바로 호출할 수 있는 것이다.
해당 코드들의 캡쳐가 들어가면 좀 더 관계파악이 쉬워질 것 같아요~

2020-10-01 14:42 UTC, pci2676 commented on _posts/2020-09-30-collection-stream-for-each.md
> +## parallelStream
Collection.forEach과 Stream.forEach 두개의 차이를 다루는데 parallelStream 얘기는 조금 글의 개연성이 떨어지는 느낌이 들었어요

2020-10-01 14:42 UTC, pci2676 commented on _posts/2020-09-30-collection-stream-for-each.md
> +ConcurrentModificationException이란 Collection이 반복되는 동안 Collection을 수정할 때 일반적으로 발생하는 예외이다.
`Collection이 반복되는 동안 Collection을 수정할 때 일반적으로 발생하는 예외이다.`
Collection으로 한정지을 수는 없는 Exception 같아요~
대표적인 예가 Collection이라는 설명이 더 나을것 같아요~

2020-10-01 14:42 UTC, pci2676 commented on _posts/2020-09-30-collection-stream-for-each.md
> +Collection.forEach의 경우엔 수정을 감지한 즉시 ConcurrentModificationException을 던지며 프로그램을 멈춘다. 아래의 코드는 List element가 짝수이면 remove 하는 Consumer를 forEach로 돌린 것이다. 코드와 실행 결과를 보자
```suggestion
Collection.forEach의 경우엔 수정을 감지한 즉시 ConcurrentModificationException을 던지며 프로그램을 멈춘다. 아래의 코드는 List의 element가 짝수이면 remove 하는 Consumer를 forEach로 돌린 것이다. 코드와 실행 결과를 보자
```

2020-10-01 14:42 UTC, pci2676 commented on _posts/2020-09-30-collection-stream-for-each.md
> +}
```suggestion
    @Test
    void test() {
        List<Integer> nums = new ArrayList<>(Arrays.asList(1, 2, 3, 4, 5, 6));

        Consumer<Integer> removeIfEven = num -> {
            System.out.println(num);
            if (num % 2 == 0) {
                nums.remove(num);
            }
        };

        assertThatThrownBy(() -> nums.forEach(removeIfEven))
                .isInstanceOf(ConcurrentModificationException.class);
    }
```

테스트 코드로 작성하고 테스트가 통과하는 스크린샷이 더 좋을 것 같다는 제 생각입니다

2020-10-01 14:42 UTC, pci2676 commented on _posts/2020-09-30-collection-stream-for-each.md
> +}
메세지로 2번째 원소에서 exception이 발생했다는 것을 확인해주면 되겠네요~

2020-10-01 14:42 UTC, pci2676 commented on _posts/2020-09-30-collection-stream-for-each.md
> +Collection.forEach처럼 지워지자마자 예외를 던지는 것이 아니라 리스트를 끝까지 돌고 예외를 던진다. 위의 실행 결과에서는 NullPointerException이 터졌는데 ConcurrentModificationException이 나오는 경우도 있고 안 나오는 경우도 있어서 ConcurrentModificationException에 의존해서
`@RepeatedTest`로 만번 테스트를 실행했을때 한번도 ConcurrentModificationException 가 발생하지 않고 NullPointerException 만 발생했는데 확인한번 해주실수 있나요?

2020-10-08 07:08 UTC, kimevanjunseok requested changes
둔덩 글 잘 읽었습니다!!
몇 가지 피드백 남깁니다!!

2020-10-08 07:08 UTC, kimevanjunseok commented on _posts/2020-09-30-collection-stream-for-each.md
> +위의 예제에서처럼 단순 반복이 목적이라면 Stream.forEach는 stream()으로 생성된 Stream 객체가 버려지는 오버헤드가 있기에, filter, map 등의 Stream 기능들과 함께 사용할 때만 Stream.forEach를 사용하고 나머지의 경우엔 Collection.forEach를 쓰는 것이 좋아 보인다.
```suggestion
위의 예제처럼 단순 반복이 목적이라면 Stream.forEach는 stream()으로 생성된 Stream 객체가 버려지는 오버헤드가 있기에, filter, map 등의 Stream 기능들과 함께 사용할 때만 Stream.forEach를 사용하고 나머지의 경우엔 Collection.forEach를 쓰는 것이 좋아 보인다.
```

2020-10-16 07:56 UTC, DunDung commented on _posts/2020-09-30-collection-stream-for-each.md
> +Collection.forEach는 따로 객체를 생성하지 않고 forEach 메서드를 호출한다. forEach 메서드는 Iterable 인터페이스의 default 메서드인데, Collection 인터페이스에서 Iterable 인터페이스를 상속하고 있기에 바로 호출할 수 있는 것이다.
맞는 말씀이세요!! 캡처면 어떤 클래스인지 잘안보여서 코드블록 삽입해서 반영했습니다 :)

2020-10-16 07:57 UTC, DunDung commented on _posts/2020-09-30-collection-stream-for-each.md
> +## parallelStream
헙... parallelStream 메서드도 반환하는게 Stream 객체여서 내용에 넣었는데 빼는게 나을까요ㅠㅠㅠ??? 비밥의 의견에 전적으로 따르겠슴다

2020-10-16 08:00 UTC, DunDung commented on _posts/2020-09-30-collection-stream-for-each.md
> +ConcurrentModificationException이란 Collection이 반복되는 동안 Collection을 수정할 때 일반적으로 발생하는 예외이다.
맞는 말씀입니다!!! 수정했어요 👍

2020-10-16 08:27 UTC, DunDung commented on _posts/2020-09-30-collection-stream-for-each.md
> +    // 출력 순서가 다르다.
완전 그럴 것 같네요! 반영했습니다 :)

2020-10-16 08:27 UTC, DunDung commented on _posts/2020-09-30-collection-stream-for-each.md
> +}
반영했습니다!

2020-10-16 08:27 UTC, DunDung commented on _posts/2020-09-30-collection-stream-for-each.md
> +Collection.forEach처럼 지워지자마자 예외를 던지는 것이 아니라 리스트를 끝까지 돌고 예외를 던진다. 위의 실행 결과에서는 NullPointerException이 터졌는데 ConcurrentModificationException이 나오는 경우도 있고 안 나오는 경우도 있어서 ConcurrentModificationException에 의존해서
제가 검증도 안해보고 다른 글을 너무 믿었었네요 ㅠㅠㅠㅠ 패러럴스트림을 쓸 때만 ConcurrentModificationException이 나오네요.. 감사합니다 글 수정했어요!

2020-10-17 10:31 UTC, kimevanjunseok approved these changes

2020-10-19 14:10 UTC, pci2676 approved these changes

2020-11-05 23:19 UTC, pobiconan commented on _posts/2020-09-30-collection-stream-for-each.md
> +    }
들여쓰기가 맞지 않네요.

2020-11-07 07:30 UTC, DunDung commented on _posts/2020-09-30-collection-stream-for-each.md
> +    }
수정했습니다!

2020-11-20 01:25 UTC, merged