[스티치] 코드 커버리지가 뭔가요?
woowacourse/javable pull request #240
Opened 2020-10-25 11:31 UTC by lxxjn0

closes #239

2020-10-30 06:03 UTC, KIMSIYOUNG requested changes
안녕하세요 스티치!
항상 글이 매우 깔끔한 전개인 것 같아요ㅎㅎㅎ
존댓말과 반말이 같이 있는데 이 부분만 수정해주세요!
개인적인 궁금함도 하나 달았는데, 코멘트 주시면 감사하겠습니다!

2020-10-30 06:03 UTC, KIMSIYOUNG commented on _posts/2020-10-24-code-coverage.md
> +위의 코드를 테스트한다고 가정해보겠습니다. `x = -1`을 테스트 데이터로 사용할 경우, if 문의 조건을 통과하지 못하기 때문에 3번 코드는 실행되지 못합니다. 총 4개의 라인에서 1, 2, 4번의 라인만 실행되므로 **구문 커버리지**는 `3 / 4 * 100 = 75(%)`가 됩니다.
전체적으로 존댓말과 반말이 공존하는 것 같아요!
반말이 국룰이라고 알고 있으니 수정하면 좋을 것 같네요ㅎㅎ

2020-10-30 06:03 UTC, KIMSIYOUNG commented on _posts/2020-10-24-code-coverage.md
> +위의 세 가지 코드 커버리지 중에서 구문 커버리지가 가장 대표적으로 많이 사용되고 있습니다.
왜 구문 커버리지를 자주 사용하나요? 다른 커버리지들이 더 기준이 엄격한 것 같은데 따로 이유가 있나요?

2020-10-30 06:03 UTC, KIMSIYOUNG commented on _posts/2020-10-24-code-coverage.md
> +> - [구조적 커버리지(Coverage)의 정의와 종류 - 슈어소프트테크](https://blog.naver.com/PostView.nhn?blogId=suresofttech&logNo=221833396343&parentCategoryNo=&categoryNo=155&viewDate=&isShowPopularPosts=false&from=postView
종류와 각각의 장단에 대해 궁금했는데, 링크로 걸려있네요! 감사합니다.

2020-11-07 15:41 UTC, yeonnseok requested changes
스티치! 코드 커버리지 글 잘읽었습니다!
결론 부분에서 정리를 잘해주신것 같네요 👍
몇 가지 피드백 남겨보았습니다~
그리구 글 전체적으로 경어체를 사용하고 계시는데 javable의 다른 글들과의 통일성을 위해서 평어체로 변경하는게 어떨까요?(예전에 저도 관련 피드백을 받은적이 있어서요 ㅎㅎ)

2020-11-07 15:41 UTC, yeonnseok commented on _posts/2020-10-24-code-coverage.md
> +조건 커버리지를 기준으로 테스트를 진행할 경우, **구문 커버리지와 결정 커버리지를 만족하지 못하는 경우가 존재**할 수 있습니다.
조건 커버리지를 기준으로 테스트를 진행하는 경우, 나머지 두 커버리지를 만족하지 못한다는 표현이 무슨 의미인지 조금 와닿지 않는 것 같아요!
각기 다른 기준으로 커버리지를 측정하고 있는데, 나머지 커버리지를 반드시 만족해야 하는 걸까요?

2020-11-07 15:41 UTC, yeonnseok commented on _posts/2020-10-24-code-coverage.md
> +위의 세 가지 코드 커버리지 중에서 구문 커버리지가 가장 대표적으로 많이 사용되고 있습니다.
제 생각에도 독자들이 가장 궁금해할 포인트인 것 같아요!

2020-11-09 13:03 UTC, lxxjn0 commented on _posts/2020-10-24-code-coverage.md
> +그래서 이번 글에서는 **코드 커버리지**가 무엇인지, 그리고 왜 코드 커버리지를 체크해야 하는지에 대해 소개해보도록 하겠습니다.
찾아보니 테스트 커버리지란 말보다는 코드 커버리지라는 말이 더 많이 쓰이더라고요. 그래서 이번 글에서도 전체적으로 코드 커버리지라는 단어를 사용하였습니다 :)

2020-11-09 13:03 UTC, lxxjn0 commented on _posts/2020-10-24-code-coverage.md
> +위의 코드를 테스트한다고 가정해보겠습니다. `x = -1`을 테스트 데이터로 사용할 경우, if 문의 조건을 통과하지 못하기 때문에 3번 코드는 실행되지 못합니다. 총 4개의 라인에서 1, 2, 4번의 라인만 실행되므로 **구문 커버리지**는 `3 / 4 * 100 = 75(%)`가 됩니다.
전체적으로 수정하였습니다 :)

2020-11-09 13:06 UTC, lxxjn0 commented on _posts/2020-10-24-code-coverage.md
> +![프로젝트 요구사항](../images/2020-10-24-project-mission.png)
아무래도 주어진 미션을 중간에 잘라서 보여주기가 애매할 것 같아서 전체적으로 캡쳐해서 사용했어요!
블로그 엔진을 사용해서 확인하면 너무 크게 보이진 않는데 그대로 둬도 괜찮을까요?? 😢 ㅎㅎㅎㅎㅎ

2020-11-09 13:06 UTC, lxxjn0 commented on _posts/2020-10-24-code-coverage.md
> +코드 커버리지는 소프트웨어의 **테스트 케이스가 얼마나 충족되었는지를 나타내는 지표** 중 하나입니다. 테스트를 진행하였을 때 **'코드 자체가 얼마나 실행되었느냐'**는 것이고, 이는 **수치**를 통해 확인할 수 있습니다.
해당 부분을 블로그 엔진을 통해 확인하면 제대로 볼드처리가 되어있어서 그대로 두도록 하겠습니다 :)

2020-11-09 13:07 UTC, lxxjn0 commented on _posts/2020-10-24-code-coverage.md
> +먼저 코드의 구조를 살펴보면 크게 **구문(*Statement*), 조건(*Condition*), 결정(*Decision*)**의 구조로 이루어져 있습니다. 코드 커버리지는 이러한 코드의 구조를 **얼마나 커버했느냐에 따라 측정기준이 나뉘게 됩니다.**
해당 부분도 위와 동일하게 블로그에는 제대로 적용됨을 볼 수 있었습니다 :)

2020-11-09 13:10 UTC, lxxjn0 commented on _posts/2020-10-24-code-coverage.md
> +
아, 소제목이 내용을 이해하는데 혼동을 준 것 같네요 ㅜㅜ
사실 코드 커버리지 측정 방법에 대한 것(라인, 바이트, 브랜치 등..)은 분석 도구에 많이 의존적인 것 같아서 해당 도구들이 사용하는 방법(기준)을 이번 글에서 설명하려고 했어요.
소제목을 어떤 기준으로 측정할까? 와 같은 느낌으로 바꾸도록 하겠습니다 :)

2020-11-09 13:17 UTC, lxxjn0 commented on _posts/2020-10-24-code-coverage.md
> +조건 커버리지를 기준으로 테스트를 진행할 경우, **구문 커버리지와 결정 커버리지를 만족하지 못하는 경우가 존재**할 수 있습니다.
아 조건 커버리지를 만족하도록(100%) 테스트 코드를 작성하더라도 다른 커버리지는 100% 만족하지 못할 수 있다는 말이었어요.
제가 다시 읽어봐도 해당 부분이 충분히 혼란이 올 수 있을 것 같네요.
조금 더 문장을 다듬어보도록 하겠습니다 :)

아 우선 혹시 마지막 문장이 질문이시라면 제가 아는 바로는 JaCoCo와 같은 도구는 커버리지의 종류를 선택할 수 있는 것으로 알고 있습니다. 라인 커버리지, 브랜치 커버리지 등 다양한 커버리지를 통해 분석이 가능한데 하나의 커버리지를 100% 만족한다고 다른 커버리지도 만족한다고 보장할 수 없습니다.
코드에 if문이 존재하는데, 만약 이 조건문이 참인 경우만 테스트하는 코드를 작성하면 모든 라인에 대해서는 커버가 가능합니다(라인 커버리지). 그러나 거짓인 경우에 대한 테스트 코드는 존재하지 않기 때문에 브랜치 커버리지는 만족하지 못하겠죠. 그래서 보다 안정적인 커버리지를 가지고 싶다면 다양한 커버리지에 대해 최대한 만족하도록 테스트를 작성하는 것이 좋다고 생각합니다.

궁금한 점에 대한 답변이 이게 아닐 수 있지만 혹시 잘못된 부분이나 다른 의견이 있으시다면 언제든지 말씀해주시면 감사하겠습니다 :)

2020-11-09 13:27 UTC, lxxjn0 commented on _posts/2020-10-24-code-coverage.md
> +조건 커버리지를 기준으로 테스트를 진행할 경우, **구문 커버리지와 결정 커버리지를 만족하지 못하는 경우가 존재**할 수 있습니다.
작성한 글에도 좀 더 상세한 설명을 추가해봤습니다 :)

2020-11-10 04:31 UTC, yeonnseok commented on _posts/2020-10-24-code-coverage.md
> +![프로젝트 요구사항](../images/2020-10-24-project-mission.png)
넵 알겠습니다 ㅎㅎ

2020-11-10 04:32 UTC, yeonnseok commented on _posts/2020-10-24-code-coverage.md
> +조건 커버리지를 기준으로 테스트를 진행할 경우, **구문 커버리지와 결정 커버리지를 만족하지 못하는 경우가 존재**할 수 있습니다.
확인했습니다! 훨씬 의미가 명확해진것 같습니다!

2020-11-10 04:34 UTC, yeonnseok approved these changes
피드백 반영하느라 고생하셨습니다!
좋은 글 감사합니다~

2020-11-20 06:12 UTC, KIMSIYOUNG approved these changes
리뷰 반영하느라 고생하셨습니다!

2020-12-16 14:38 UTC, merged