[비밥] 정적, 비정적 내부 클래스 알고 사용하기
woowacourse/javable pull request #248
Opened 2020-11-05 05:28 UTC by pci2676

[글](https://github.com/woowacourse/javable/blob/doc%2Fnested-class/_posts/2020-11-05-nested-class.md)

원래 중첩 클래스에 대해 전반적으로 다뤄볼까 했는데 그렇게 되면 너무 겉핥기 식으로 다루게 될 것 같아서 정적, 비정적 내부 클래스로 범위를 줄였습니다.

close #245

2020-11-07 15:27 UTC, hwookim requested changes
안녕하세요 비밥!

내부 클래스를 별로 구현해본 적이 없어 알지 못했는데, 이번 기회에 많은 걸 알게 되었네요.
좋은 글 잘 읽었습니다.😄

몇가지 간단한 리뷰 남겼으니 확인 부탁드려요!

2020-11-08 07:56 UTC, kimevanjunseok approved these changes
비밥!!! 고생하셨어요!!!
늦은 피드백드려서 죄송합니다.😭😭
몇 가지 남겼습니다!! 확인해보세용!!

2020-11-08 07:56 UTC, kimevanjunseok commented on _posts/2020-11-05-nested-class.md
> +tags: ["java"]
태그를 추가하는 것은 어때요??😊
자바 하나는 너무 광범위한 것 같습니다!!

2020-11-08 07:56 UTC, kimevanjunseok commented on _posts/2020-11-05-nested-class.md
> +    	private int b;
들여쓰기가 아래 코드와  다릅니다!!!

2020-11-08 07:56 UTC, kimevanjunseok commented on _posts/2020-11-05-nested-class.md
> +글로만 보면 믿지 않을 독자를 위해 직접 보여주도록 하겠다. 아래 코드는 실험에 사용할 클래스이다.
저도 같은 생각입니다.😭😭 말을 조금 더 덜 공격적이게 말하면 좋을 것 같아요.😊

2020-11-08 07:56 UTC, kimevanjunseok commented on _posts/2020-11-05-nested-class.md
> +**비정적 클래스를 어댑터 패턴을 이용하여 바깥 클래스를 다른 클래스로 제공**할 때 사용하면 좋다. 이러한 케이스로 `HashMap`의 `keySet()` 이 있다. `keySet()` 을 사용하면 Map의 key에 해당하는 값들을 Set으로 반환해 주는 데 어댑터 패턴을 이용해서 Map을 Set으로 제공한다.
혹시 `` 이것을 사용하는 기준이 있나요?
글을 읽을 때 메서드라고 생각했는데 아니더라구요!! `HashMap`에는 사용하고 위에서 클래스를 나타낼 때도 사용하셨는 데 안 사용할 때도 있어서 궁금합니다!!😊😊

2020-11-08 08:02 UTC, pci2676 commented on _posts/2020-11-05-nested-class.md
> +javap -p build/classes/java/main/com/javabom/nested/Outer\$StaticInner.class
인텔리제이가 있으면 쉽게 확인할 수 있겠지만 사용하지 않는 독자도 많을것 같아요~

2020-11-08 08:02 UTC, pci2676 commented on _posts/2020-11-05-nested-class.md
> +    	private int b;
눈썰미가 좋으시군요!

2020-11-08 08:05 UTC, pci2676 commented on _posts/2020-11-05-nested-class.md
> +**비정적 클래스를 어댑터 패턴을 이용하여 바깥 클래스를 다른 클래스로 제공**할 때 사용하면 좋다. 이러한 케이스로 `HashMap`의 `keySet()` 이 있다. `keySet()` 을 사용하면 Map의 key에 해당하는 값들을 Set으로 반환해 주는 데 어댑터 패턴을 이용해서 Map을 Set으로 제공한다.
구조체랑 코드에 해당하는 부분들을 감쌌어요!
누락된 부분 채워넣었습니다 ㅎㅎ

2020-11-08 08:07 UTC, pci2676 commented on _posts/2020-11-05-nested-class.md
> +tags: ["java"]
흠.. 저는 자바말고 다른 태그를 추가하기 애매하다고 생각합니다!

2020-11-09 11:32 UTC, hwookim approved these changes
반영하신 부분 잘 봤습니다 👍
이만 어프로브 할게요

2020-12-16 14:39 UTC, merged