[둔덩] 자바 제네릭(Generics) 기초
woowacourse/javable pull request #254
Opened 2020-11-09 13:52 UTC by DunDung

두 편으로 나눠서 쓸 계획입니다!

fixes: #253

2020-11-11 16:52 UTC, minuyim requested changes
안녕하세요 둔덩!
제네릭 글 잘봤습니다. 기초여도 항상 어렵다고 느껴지는게 제네릭부분인 것 같습니다.
간단한 리뷰 남겼습니다. 확인해주세요.

2020-11-11 16:52 UTC, minuyim commented on _posts/2020-11-09-generics-basic.md
> +이번 글에서는 제네릭을 왜 사용해야 하는지와 제네릭으로 구현된 클래스 및 메서드를 읽을 때 필요한 기초적인 내용을 알아보았다. 자바 문법을 배울 때 스쳐 지나갔던 제네릭이 공부할수록 깊은 내용이 많고 모르는 내용도 많다는 것을 느꼈다. 다음 글에서는 이 글에서 못 다룬 wild card와 Type eraser 그리고 제네릭을 사용할 때의 주의사항 등을 살
`Type eraser` => `Type erasure` 오타네요.

2020-11-11 16:52 UTC, minuyim commented on _posts/2020-11-09-generics-basic.md
> +![](![](../images/2020-11-09-generics-2.png)
`![](` 이부분이 중복되네요.

2020-11-11 16:52 UTC, minuyim commented on _posts/2020-11-09-generics-basic.md
> +CharSequence 인터페이스 하위 객체들만 데이터 타입으로 지정할 수 있게 함으로써 인스턴스 변수 name에 문자열 관련 타입만 지정할 수 있게 되었다.
추가로 CharSequence(제한된 인터페이스)에서 정의된 메서드도 실행할 수 있다는 점을 알려주면 좋을 것 같습니다.
ex) name.charAt(0)이 사용가능하겠네요.

2020-11-11 16:52 UTC, minuyim commented on _posts/2020-11-09-generics-basic.md
> +위와 같은 Car 클래스에서 from 메서드와 printEqualsCar 메서드가 제네릭 메서드이다. 제네릭 메서드 타입 `<T>`를 리턴 타입 앞에 붙여서 표시하므로 헷갈릴 수 있는데 메서드 리턴 타입과 제네릭 타입은 관계가 없다. 어떤 제네릭 타입을 사용할지를 리턴 타입 앞에 붙여서 컴파일러에게 알려줄 뿐이다.
제네릭 클래스와 제네릭 메서드가 같은 T를 쓰고 있어서 헷갈릴 수도 있을 것 같아요. 이부분에 대해서 추가적으로 설명해주면 좋을 것 같습니다.

2020-11-11 16:52 UTC, minuyim commented on _posts/2020-11-09-generics-basic.md
> +    }
코드보다가 제가 제네릭을 잘 몰라 헷갈리는 부분이 있어 질문드려봅니다. ㅠ
이 메소드에서는 해당 Car instance의 타입과 매개변수로 오는 Car의 타입이 다르게 올 수 있는 건가요?

2020-11-19 07:54 UTC, KIMSIYOUNG approved these changes
안녕하세요 둔덩 전체적으로 잘 작성해주셨네요!
제가 잘 모르는 부분에 대해서 질문 하나 남겼습니다.
저는 따로 고칠부분이 없는 것 같아서 어프루브 하겠습니다!

2020-11-19 07:54 UTC, KIMSIYOUNG commented on _posts/2020-11-09-generics-basic.md
> +제네릭이란 JDK 1.5부터 도입한 클래스 내부에서 사용할 데이터 타입을 외부에서 지정하는 기법이다.
정의가 명확하네요👏

2020-11-19 07:54 UTC, KIMSIYOUNG commented on _posts/2020-11-09-generics-basic.md
> +또한 제네릭 클래스가 아닌 일반 클래스에서도 제네릭 메서드를 사용할 수 있다는 점을 기억하자.
저는 리턴 타입 앞에 사용하는 T가 매개변수로 들어오는 T라는 것을 명시해주는 것으로 알고 있는데,
잘 못 알고 있는건가요? 제네릭 메서드의 의미는 알겠는데, 저와 같이 이해해도 괜찮나요?

2020-11-19 07:54 UTC, KIMSIYOUNG commented on _posts/2020-11-09-generics-basic.md
> +이번 글에서는 제네릭을 왜 사용해야 하는지와 제네릭으로 구현된 클래스 및 메서드를 읽을 때 필요한 기초적인 내용을 알아보았다. 자바 문법을 배울 때 스쳐 지나갔던 제네릭이 공부할수록 깊은 내용이 많고 모르는 내용도 많다는 것을 느꼈다. 다음 글에서는 이 글에서 못 다룬 wild card와 Type eraser 그리고 제네릭을 사용할 때의 주의사항 등을 살
제네릭의 일반적인 설명도 좋지만, 어떤 상황에서 활용할 수 있는지 알려주면 좋을 것 같아요.
3편 연재 생각은 없으신가요~~?

2020-11-20 13:23 UTC, DunDung commented on _posts/2020-11-09-generics-basic.md
> +이번 글에서는 제네릭을 왜 사용해야 하는지와 제네릭으로 구현된 클래스 및 메서드를 읽을 때 필요한 기초적인 내용을 알아보았다. 자바 문법을 배울 때 스쳐 지나갔던 제네릭이 공부할수록 깊은 내용이 많고 모르는 내용도 많다는 것을 느꼈다. 다음 글에서는 이 글에서 못 다룬 wild card와 Type eraser 그리고 제네릭을 사용할 때의 주의사항 등을 살
감사합니다. 수정했어요!

2020-11-20 13:24 UTC, DunDung commented on _posts/2020-11-09-generics-basic.md
> +![](![](../images/2020-11-09-generics-2.png)
앗... 매의눈 감사합니다 :)

2020-11-20 13:24 UTC, DunDung commented on _posts/2020-11-09-generics-basic.md
> +CharSequence 인터페이스 하위 객체들만 데이터 타입으로 지정할 수 있게 함으로써 인스턴스 변수 name에 문자열 관련 타입만 지정할 수 있게 되었다.
오오 맞는 말씀이십니다. 바로 반영했습니다!

2020-11-20 13:25 UTC, DunDung commented on _posts/2020-11-09-generics-basic.md
> +위와 같은 Car 클래스에서 from 메서드와 printEqualsCar 메서드가 제네릭 메서드이다. 제네릭 메서드 타입 `<T>`를 리턴 타입 앞에 붙여서 표시하므로 헷갈릴 수 있는데 메서드 리턴 타입과 제네릭 타입은 관계가 없다. 어떤 제네릭 타입을 사용할지를 리턴 타입 앞에 붙여서 컴파일러에게 알려줄 뿐이다.
네 그부분이 충분히 헷갈릴 수 있겠더라구요.. 그래서 제네릭 메서드 타입을 수정하는 방향으로 리뷰 반영해 보았습니다. 확인 한 번 더 부탁드려용 :)

2020-11-20 13:25 UTC, DunDung commented on _posts/2020-11-09-generics-basic.md
> +    }
제가 헷갈리게 글을 썼네요.. 라테가 이해한 게 맞습니다!

2020-11-20 13:25 UTC, DunDung commented on _posts/2020-11-09-generics-basic.md
> +제네릭이란 JDK 1.5부터 도입한 클래스 내부에서 사용할 데이터 타입을 외부에서 지정하는 기법이다.
ㅋㅋㅋㅋ감사합니다 👍

2020-11-20 13:35 UTC, DunDung commented on _posts/2020-11-09-generics-basic.md
> +또한 제네릭 클래스가 아닌 일반 클래스에서도 제네릭 메서드를 사용할 수 있다는 점을 기억하자.
음.. 리턴 타입앞에 T는 그 매개 변수 뿐 아니라 
리턴 타입 등 메서드에서 사용하는 T를 전부 명시해주는 것이라고 알고있습니다!

2020-11-20 13:36 UTC, DunDung commented on _posts/2020-11-09-generics-basic.md
> +이번 글에서는 제네릭을 왜 사용해야 하는지와 제네릭으로 구현된 클래스 및 메서드를 읽을 때 필요한 기초적인 내용을 알아보았다. 자바 문법을 배울 때 스쳐 지나갔던 제네릭이 공부할수록 깊은 내용이 많고 모르는 내용도 많다는 것을 느꼈다. 다음 글에서는 이 글에서 못 다룬 wild card와 Type eraser 그리고 제네릭을 사용할 때의 주의사항 등을 살
기회가 된다면... 어떤 상황에서 사용하는지를 3편으로 써서 올려보겠습니다...!

2020-11-21 12:19 UTC, minuyim approved these changes
반영 확인했습니다. 수고하셨어요!

2020-12-16 14:39 UTC, merged