[파피] 방어적 복사와 Unmodifiable
woowacourse/javable pull request #288
Opened 2021-04-26 04:28 UTC by TaewanKimmmm

초안 작성했습니다!
많은 피드백 부탁드립니다!

2021-04-29 12:09 UTC, xlffm3 requested changes
안녕하세요 파피~ 글 잘 읽었어요. 피드백 남긴 부분 반영해주시고 다시 리뷰요청부탁드려요~

2021-05-02 03:26 UTC, da-nyee requested changes
안녕하세요 파피~! 글 잘 읽었습니다 ㅎㅎ
전체적으로 이해하기 쉽고 잘 정리된 글이란 느낌을 받았어요!
코멘트 하나 남겼는데 확인하고 반영해주시면 감사하겠습니다~! 🙌

2021-05-02 03:26 UTC, da-nyee commented on src/content/post/2021-04-26-defensive-copy-vs-unmodifiable.md
> +결론부터 말하자면 아니다. 위에서도 알 수 있듯 컬렉션의 주소만 공유하지 않을 뿐, 내부 요소들의 주소는 공유하고 있다.
저도 케빈 의견에 동의합니다!
방어적 복사와 깊은 복사의 차이점이 설명되면 더 좋을 것 같아요!

2021-05-04 01:23 UTC, xlffm3 approved these changes
안녕하세요 파피 피드백은 잘 반영해주셨는데 오타가 좀 있는것같아서 그 부분만 수정하시면될것같습니다!

2021-05-04 01:23 UTC, xlffm3 commented on src/content/post/2021-04-26-defensive-copy-vs-unmodifiable.md
> +    crewNames.getName(0).setName("Sally"); // crewNames의 names: Fafi, Sally
음 이러면 Sally Kevin이 되는게 아닐까요? 코드가 잘못된것같습니다.

2021-05-08 14:59 UTC, da-nyee approved these changes
안녕하세요 파피! 🙌 코멘트 반영하신 것 확인했습니다 ㅎㅎ
방어적 복사와 unmodifiable 주제 정말 좋네요 👍
이번 글은 여기서 approve 하겠습니다! 수고하셨습니다~!

2021-05-15 02:38 UTC, gracefulBrown approved these changes
전반적으로 읽기 편한 글 이었어요!
앞선 피드백을 통해 내용 전달도 원활한 거 같아서 바로 머지 해도 좋을 것 같아요ㅎㅎ
고생하셨습니다~

2021-05-15 02:38 UTC, merged