[와일더] Java 의 Stack 대신 Deque
woowacourse/javable pull request #321
Opened 2021-05-10 12:18 UTC by lns13301

프로필이 적용되지 않은 버전이다보니 로컬에서 돌리면 해당 페이지에 들어갈 수 없습니다.
첫 글이 Merge 되고 나면 문제없이 로컬에서 볼 수 있을 겁니다.
잘부탁드립니다!

2021-05-13 02:33 UTC, wannte requested changes
와일더 요번에도 리뷰를 맡았네요!
좋은 설명 잘읽었습니다~ 몇가지 리뷰 남겼어요!

2021-05-13 02:33 UTC, wannte commented on src/content/post/2021-05-10-stack-vs-deque.md
> +Deque 인터페이스를 사용하면 필요한 모든 스택 작업을 제공하기 때문에 편리하다. 또한, 작업에 Lock 을 사용하지 않기 때문에 단일 스레드에서도 문제가 발생하지 않는다. 다만, 다중 스레드 실행의 경우 문제가 될 수 있지만 ArrayDeque 에 대한 동기화 데코레이터를 구현할 수 있다. 이는 JCF 의 Stack 클래스와 유사하게 수행되지만, St
`ArrayDeque 에 대한 동기화 데코레이터를 구현할 수 있다` 간단히 보여주면 이해에 도움이 될 것 같아요!

2021-05-13 02:33 UTC, wannte commented on src/content/post/2021-05-10-stack-vs-deque.md
> +멀티스레드 환경과 상관없이 자바에서의 Stack 은 대부분의 조건에서 성능 저하를 일으키기 때문에 사용을 지양한다. 대신에 Deque 의 구현체를 사용한다. 메모리 소모량이 적을 때는 iterate 효율이 좋은 ArrayDeque 를 사용하고 스택의 사이즈가 커질 때는 LinkedList 를 사용한다. 또한, 멀티스레드 환경에서는 각각 LinkedBloc
`메모리 소모량이 적을 때는 iterate 효율이 좋은 ArrayDeque 를 사용하고 스택의 사이즈가 커질 때는 LinkedList 를 사용한다.` 이 부분은 본문에서 설명되지 않은 부분인데요! 왜 그런지 근거를 본문에 추가하면 좋을 것 같아요

2021-05-13 02:33 UTC, wannte commented on src/content/post/2021-05-10-stack-vs-deque.md
> +
추가적으로 실제 stack 과 deque를 이용하여 구현한 코드도 추가되면 이해에 도움이 될것같아요!

2021-05-13 15:15 UTC, dusdn1702 reviewed
와일더 안녕하세요 글 잘 읽었습니다.ㅎㅎ
추가적으로 설명이 더해졌으면 하는 부분들에 대해서 피드백 남겨두었습니다!

2021-05-13 15:15 UTC, dusdn1702 commented on src/content/post/2021-05-10-stack-vs-deque.md
> +후입선출(LIFO) 자료구조를 구현한 자바의 클래스다. 자바의 Stack 은 List Collection 의 Vector 를 상속받은 스택 메모리 구조의 클래스를 제공한다. 배열 기반 데이터 구조로 인덱스로 요소에 액세스 할 수 있다.
후입선출, 선입선출에 대해 간략히 설명해주면 어떨까요!??

2021-05-13 15:15 UTC, dusdn1702 commented on src/content/post/2021-05-10-stack-vs-deque.md
> +선입선출(FIFO) 자료구조를 구현한 자바의 인터페이스다.
큐는 인덱스로 요소에 접근 가능한지 궁금해지네요..~!

2021-05-13 15:15 UTC, dusdn1702 commented on src/content/post/2021-05-10-stack-vs-deque.md
> +즉, Stack 대신 Deque 의 구현체인 ArrayDeque 사용을 제안하고 있다. Java 에서 Stack 은 Thread Safe 하기 위해서 만들어졌지만 단순한 Iterator 의 탐색 작업에서도 get() 메서드 실행 시 계속해서 한 번만 걸어주면 될 lock 을 매번 걸고 닫음으로 쓸데없는 오버헤드가 발생한다. 따라서 Vector 를 상속받은
lock을 걸고 여는 것이겠죠..?
thread safe을 위해 만들어진 stack이 오버헤드가 많이 발생함에 따라 비효율적이어서 thread safe하지 않다고 볼 수 있는건가요..? (정말 궁금해서 드리는 질문입니다..)

2021-05-13 15:15 UTC, dusdn1702 commented on src/content/post/2021-05-10-stack-vs-deque.md
> +  - 매번 Lock 이 발생하게 되므로 오버헤드가 커진다.
이렇게 중복으로 되는 것보단 위에 언급한 단점 외의 단점을 알려주는 것이 어떨까요?!?

2021-05-13 15:15 UTC, dusdn1702 commented on src/content/post/2021-05-10-stack-vs-deque.md
> +Deque 인터페이스를 사용하면 필요한 모든 스택 작업을 제공하기 때문에 편리하다. 또한, 작업에 Lock 을 사용하지 않기 때문에 단일 스레드에서도 문제가 발생하지 않는다. 다만, 다중 스레드 실행의 경우 문제가 될 수 있지만 ArrayDeque 에 대한 동기화 데코레이터를 구현할 수 있다. 이는 JCF 의 Stack 클래스와 유사하게 수행되지만, St
동감해요! 어떻게 초기 용량 설정 문제를 해결했는지 궁금하네요 ㅎㅎ

2021-05-13 15:15 UTC, dusdn1702 commented on src/content/post/2021-05-10-stack-vs-deque.md
> +- 두 번째 쓰레드가 코드 A 를 실행한다. 두 스레드 모두 같은 object 가 담긴다.
쓰레드 vs 스레드 통일하는건 어떤가요..?^0^

2021-05-13 15:15 UTC, dusdn1702 commented on src/content/post/2021-05-10-stack-vs-deque.md
> +멀티스레드 환경과 상관없이 자바에서의 Stack 은 대부분의 조건에서 성능 저하를 일으키기 때문에 사용을 지양한다. 대신에 Deque 의 구현체를 사용한다. 메모리 소모량이 적을 때는 iterate 효율이 좋은 ArrayDeque 를 사용하고 스택의 사이즈가 커질 때는 LinkedList 를 사용한다. 또한, 멀티스레드 환경에서는 각각 LinkedBloc
저는 멀티스레드에서는 왜 LinkedBlockingDeque과 ConcurrentLinkedDeque을 사용하는지도 궁금해요!

2021-05-15 06:35 UTC, lns13301 commented on src/content/post/2021-05-10-stack-vs-deque.md
> +선입선출(FIFO) 자료구조를 구현한 자바의 인터페이스다.
인덱스로 접근 불가능 합니다!

2021-05-17 08:51 UTC, dusdn1702 approved these changes
피드백 반영 확인했습니다!!
글 쓰느라 수고하셨어요~~

2021-05-17 09:03 UTC, wannte approved these changes
고생했어요 와일더~

2021-05-24 09:50 UTC, gracefulBrown approved these changes
잘 작성하셨네요 👍 
읽기에 부담없는 분량에 참고 자료와 샘플 코드 까지 좋았습니다 :)
바로 머지할게요~

2021-05-24 09:50 UTC, merged