[케빈] DTO의 사용범위 및 DTO <-> Entity 간 변환 위치에 대하여
woowacourse/javable pull request #322
Opened 2021-05-10 15:06 UTC by xlffm3

안녕하세요 브라운.
javable repo에서 브랜치 따고 pr 새로보냅니다.

기존에는 service와 controller 장단점이 있다라는 논지의 글이였지만
이번에는 service에서 처리하는 것이 더 낫다라는 방향으로 글을 수정했어요.

자료를 많이 찾아봤는데

service에서 처리했을 때의 장점(controller에서 처리할때의 단점)은 많은 반면, 그 반대는 자료가 없고 크게 생각나는 경우가 없더라구요...

2021-05-13 14:50 UTC, hybeom0720 requested changes
안녕하세요! 케빈
이번 글 리뷰하러 왔는데, 케빈의 인사이트 및 해설에서 많이 배워가는 것 같아요!
특히 Level1 때 DTO에 대해 어렵고 처음 접해보는 용어가 많아서 이해가 조금 어려웠습니다.
Level1 막바지가 되서 사용하면서 많이 깨닫게 되었는데요. 
케빈의 글은 실제로 상황에 처하지 않은 독자가 읽어도, 독자와 대화를 해나가면서 해답을 찾아가는 것이 이해하기도 쉽고, 인상이 깊었습니다. 그리고 추상적으로만 알고 있는 개념들을 명확하게 정리해주는 것도 상당히 좋았습니다.
내용 관련보단, 초보 독자들이 읽었을 때, 이런 관점은 어떨까? 라는 생각에 리뷰를 남깁니다.
좋은글 감사드려요!

2021-05-13 14:50 UTC, hybeom0720 commented on src/content/post/2021-04-25-dto-layer-scope.md
> +Controller는 View로부터 들어온 사용자 요청을 해석하여 Model을 업데이트하거나 Model로부터 데이터를 받아 View로 전달하는 작업 등을 수행합니다. MVC 패턴의 장점은 Model과 View를 분리함으로써 서로의 의존성을 낮추고 독립적인 개발을 가능하게 합니다.
```
 MVC 패턴의 장점은 Model과 View를 분리함으로써 서로의 의존성을 낮추고 독립적인 개발을 가능하게 합니다. 
```
이 부분에 Controller를 사용함으로써~ 라는 늬앙스가 들어가면, 이해가 조금 더 쉬워질 것 같습니다.
하지만, 문장의 간결한 호흡을 유지하고 싶으시면 유지하셔도 좋을 것 같아요!

2021-05-13 14:50 UTC, hybeom0720 commented on src/content/post/2021-04-25-dto-layer-scope.md
> +Controller는 View와 도메인 Model의 데이터를 주고 받을 때 별도의 **DTO** 를 주로 사용합니다. 도메인 객체를 View에 직접 전달할 수 있지만, 민감한 도메인 비즈니스 기능이 노출될 수 있으며 Model과 View 사이에 의존성이 생기기 때문입니다. 물론 프로젝트가 및 특성에 따라 [DTO 사용이 불필요한 경우](http://gun
전문적인 글 인용인 것 같아서 좋은 것 같습니다.
저 글을 읽어보니, 소규모 팀이거나 프로젝트면 DTO를 활용하지 않아도 된다고 하는 것 같아요.
``` 물론 프로젝트가 및 특성 ```
에서 주로 소규모 라는 내용을 설명해도 괜찮을 것 같습니다.

2021-05-13 14:50 UTC, hybeom0720 commented on src/content/post/2021-04-25-dto-layer-scope.md
> +
제가 생각하는 것보다 더 많은 내용들이 있었군요.
리뷰하러 왔다가 많이 배우는 것 같습니다.
조금 더 첨언 하자면, 

``` java
public class User {
  public final long id;
  public final String name;
  public final String email;
  public final String password; //추가된 필드
}
```
같이 예시를 들어서 추가됬을 때, 의도치 않게 프론트에 해당 값을 전달하여 보안의 문제가 생길 수 있다를 상기시켜도 좋을 것 같아요.
하지만 케빈이 처음 의도한 것처럼 깔끔하게 전달을 하는 방향이면 유지해도 좋을 것 같습니다.

2021-05-13 14:50 UTC, hybeom0720 commented on src/content/post/2021-04-25-dto-layer-scope.md
> +    //복잡한 로직이 존재한다고 가정...
😄 😄

2021-05-13 14:50 UTC, hybeom0720 commented on src/content/post/2021-04-25-dto-layer-scope.md
> +### 4.2. DTO 사용의 경우
### 4.1 DTO 반환의 경우
### 4.2 DTO 사용의 경우
라는 제목이 조금 애매모호한 것 같습니다.
4에 Service라는 제목이 있긴 한데, 한 번 더 주어를 들어내는 것이 좋을 것 같아요!

2021-05-13 14:52 UTC, hybeom0720 approved these changes

2021-05-13 14:53 UTC, hybeom0720 commented
앗 잘못 남겼네요 ㅜㅜ 
다른 글에 리뷰 남기도록 하겠습니다.
좋은 글 잘 읽었어요!

2021-05-14 02:22 UTC, xlffm3 commented on src/content/post/2021-04-25-dto-layer-scope.md
> +Controller는 View와 도메인 Model의 데이터를 주고 받을 때 별도의 **DTO** 를 주로 사용합니다. 도메인 객체를 View에 직접 전달할 수 있지만, 민감한 도메인 비즈니스 기능이 노출될 수 있으며 Model과 View 사이에 의존성이 생기기 때문입니다. 물론 프로젝트가 및 특성에 따라 [DTO 사용이 불필요한 경우](http://gun
오타가 있었네요!

2021-05-15 03:48 UTC, gracefulBrown approved these changes
피드백 반영 확인했어요~
많은 내용을 담고 있는 포스트지만 읽는데 큰 어려움 없이 읽을 수 있는 글이었습니다!
고생 많으셨습니다~

2021-05-15 03:49 UTC, merged