[파피] Spring Boot 슬라이스 테스트
woowacourse/javable pull request #333
Opened 2021-05-18 05:24 UTC by TaewanKimmmm

늦어서 죄송합니다ㅠㅠ

초안 작성했으니 많은 피드백 부탁드립니다!!!!!!

2021-05-18 05:35 UTC, xlffm3 requested changes
안녕하세요 파피~ 글 재미있게 읽었습니다!

2021-05-18 05:35 UTC, xlffm3 commented on src/content/post/2021-05-18-slice-test.md
> +		private MockMvc mvc; // 클라이언트의 요청을 테스트할 컨트롤러로 전달하는 역할을 한다.
코드가 정렬이 되어있지 않네요.

2021-05-18 05:35 UTC, xlffm3 commented on src/content/post/2021-05-18-slice-test.md
> +예를 들면 결제 기능 개발 시에, 결제 대행 서비스로 요청을 보낸다고 가정하자.
이 부분도 간략하게 코드로 보여주면 좋을 것 같아요.

2021-05-18 05:35 UTC, xlffm3 commented on src/content/post/2021-05-18-slice-test.md
> +
이러한 Mockito given-when-then 조작을 통해 테스트를 작성하는 것은 찬반논란이 많은 것으로 아는데요.
어떨 때 Mockito 사용을 고려해야할지를 조금 더 구체적으로 작성해주면 좋을 것 같아요. 이러한 주의할 점이 있는데, 단순히 Bean들을 모두 사용할 상황이 아니라면 슬라이스 테스트를 고려해야할 더 좋은 구체적인 이유가 있을까요?

2021-05-19 07:22 UTC, da-nyee reviewed
안녕하세요, 파피! 🙌

글 잘 읽었습니다 ~!
슬라이스 테스트에 대해 덕분에 알아갑니다 ㅎㅎㅎ

코멘트 몇 개 남겼는데, 확인하고 반영해주세요 !

2021-05-19 07:22 UTC, da-nyee commented on src/content/post/2021-05-18-slice-test.md
> +따라서 @SpringBootTest 어노테이션은 어플리케이션 컨텍스트를 전체를 사용해야 하는 통합 테스트에 사용되어야한다.
```suggestion
따라서 @SpringBootTest 어노테이션은 어플리케이션 컨텍스트 전체를 사용하는 통합 테스트에 사용돼야 한다.
```

2021-05-19 07:22 UTC, da-nyee commented on src/content/post/2021-05-18-slice-test.md
> +@WebMvcTest 어노테이션을 사용하면 웹 레이어 테스트를 하는 데 필요한 **@Controller, @ControllerAdvice, @JsonComponent, Converter, GenericConverter, Filter, WebMvcConfigurer, HandlerMethodArgumentResolver** 등만 Bean으로 등록하고, 이
```suggestion
@WebMvcTest 어노테이션을 사용하면 웹 레이어 테스트를 하는 데 필요한 **@Controller, @ControllerAdvice, @JsonComponent, Converter, GenericConverter, Filter, WebMvcConfigurer, HandlerMethodArgumentResolver** 등만 Bean으로 등록한다. 이 밖에 테스트를 하는 데 필요하지 않은 컴포넌트들(ex. @Service, @Repository)은 Bean으로 등록하지 않는다.
```

2021-05-19 07:22 UTC, da-nyee commented on src/content/post/2021-05-18-slice-test.md
> +		private MockMvc mvc; // 클라이언트의 요청을 테스트할 컨트롤러로 전달하는 역할을 한다.
케빈 매의 눈이시네요 👀

2021-05-19 07:22 UTC, da-nyee commented on src/content/post/2021-05-18-slice-test.md
> +결제 대행 서비스에서는 테스트 코드에서 보낸 요청에 대해 항상 올바르지 않은 요청으로 간주할 것이다.
```suggestion
결제 대행 서비스에서는 테스트 코드에서 보낸 요청을 항상 올바르지 않은 요청으로 간주한다.
```

2021-05-19 07:22 UTC, da-nyee commented on src/content/post/2021-05-18-slice-test.md
> +그렇기 때문에 내가 원하는 결과를 던지도록 지정한 이후, 로직이 예상대로 동작하는지에 대해 확인할 수 있도록 하는 것이다.
```suggestion
그렇기 때문에 내가 원하는 결과를 던지도록 지정한 이후, 로직이 예상대로 동작하는지를 확인한다.
```

2021-05-19 07:22 UTC, da-nyee commented on src/content/post/2021-05-18-slice-test.md
> +요청부터 응답까지 모든 테스트를 Mock 기반으로 테스트하기 떄문에 실제 환경에서는 제대로 동작하지 않을 수 있다.
```suggestion
요청부터 응답까지 모든 테스트를 Mock 기반으로 테스트하기 때문에 실제 환경에서는 제대로 동작하지 않을 수 있다.
```

2021-05-19 07:22 UTC, da-nyee commented on src/content/post/2021-05-18-slice-test.md
> +Mock을 사용한다면 내부 구현도 알아야하고, 테스트 코드를 작성하며 테스트의 성공을 의도할 수 있기 때문에 완벽한 테스트라 보기 힘들다.
```suggestion
Mock을 사용한다면 내부 구현도 알아야 하고, 테스트 코드를 작성하며 테스트의 성공을 의도할 수 있기 때문에 완벽한 테스트라 보기 힘들다.
```

2021-06-13 11:17 UTC, TaewanKimmmm commented on src/content/post/2021-05-18-slice-test.md
> +따라서 @SpringBootTest 어노테이션은 어플리케이션 컨텍스트를 전체를 사용해야 하는 통합 테스트에 사용되어야한다.
아앗 ㅎㅎㅎ 감사합니당

2021-06-13 11:18 UTC, TaewanKimmmm commented on src/content/post/2021-05-18-slice-test.md
> +@WebMvcTest 어노테이션을 사용하면 웹 레이어 테스트를 하는 데 필요한 **@Controller, @ControllerAdvice, @JsonComponent, Converter, GenericConverter, Filter, WebMvcConfigurer, HandlerMethodArgumentResolver** 등만 Bean으로 등록하고, 이
훨씬 매끄럽네요 ㅎㅎ감사합니다!

2021-06-13 11:20 UTC, TaewanKimmmm commented on src/content/post/2021-05-18-slice-test.md
> +요청부터 응답까지 모든 테스트를 Mock 기반으로 테스트하기 떄문에 실제 환경에서는 제대로 동작하지 않을 수 있다.
헉..수정했습니다!

2021-06-13 11:21 UTC, TaewanKimmmm commented on src/content/post/2021-05-18-slice-test.md
> +		private MockMvc mvc; // 클라이언트의 요청을 테스트할 컨트롤러로 전달하는 역할을 한다.
수정했습니다 ㅎㅎㅎㅎㅎㅎ

2021-06-20 10:02 UTC, TaewanKimmmm commented on src/content/post/2021-05-18-slice-test.md
> +
반영하였습니다 ㅎ ㅎ

2021-06-20 10:02 UTC, TaewanKimmmm commented on src/content/post/2021-05-18-slice-test.md
> +말 그대로 레이어별로 잘라서 테스트를 한다는 것이다.
반영하였습니다!

2021-06-20 10:38 UTC, da-nyee approved these changes
안녕하세요, 파피!

피드백 반영 확인했습니다 👍
이번 주제 다시 봐도 흥미롭네요 ㅎㅎ

수고하셨습니다 👏👏

2021-06-21 07:09 UTC, xlffm3 approved these changes
안녕하세요 파피.
Mockito를 활용한 서비스 슬라이스 테스트의 주의점 등 생각해볼만한 사항에 대한 피드백 잘 반영해주셨네요!

2021-06-28 08:38 UTC, kang-hyungu requested changes
어디서 볼 수 있는지 링크도 남겨주면 좋겠어요~!

2021-06-28 08:38 UTC, kang-hyungu commented on src/content/post/2021-05-18-slice-test.md
> +`spring.io` 에서는 다음과 같이 말한다.
spring.io라고 하면 너무 광범위한데 실제 어디서 볼 수 있는지 링크는 없을까요?

2021-06-28 11:29 UTC, TaewanKimmmm commented on src/content/post/2021-05-18-slice-test.md
> +`spring.io` 에서는 다음과 같이 말한다.
링크 첨부했습니다!

2021-06-28 12:32 UTC, kang-hyungu approved these changes
파피 수고하셨어요!

2021-06-28 12:32 UTC, merged