[와일더] StreamAPI 나도 한 번 써보자!
woowacourse/javable pull request #360
Opened 2021-05-23 09:58 UTC by lns13301

우아한테크코스를 준비하는 4기, 5기... 분들을 위해서 준비한 초심자용 StreamApi 사용방법을 정리해봤습니다.
프리코스 미션에서 사용할 만한 수준으로 내용을 작성해봤는데요, 리뷰 잘부탁드립니다. 😆

2021-05-25 07:02 UTC, da-nyee requested changes
안녕하세요, 와일더! 내용 잘 읽었습니다 👍

글이 다소 긴 느낌이 있는데, 1편 / 2편 이런 식으로 나눠 작성해도 좋을 것 같아요!
코멘트 몇 개 남겼는데 확인 부탁드릴게요 ~!

2021-05-25 07:02 UTC, da-nyee commented on src/content/post/2021-05-23-stream-api-basic.md
> +IntelliJ 를 사용해서 프로그래밍하고 있다면 중간 연산 단계에서 <b>.</b> 을 입력하여 어떤 메서드를 사용할 수 있는지 확인해 보면 다양한 중간 연산을 시도해 보는 데 도움 된다.
```suggestion
IntelliJ 를 사용해서 프로그래밍하고 있다면 중간 연산 단계에서 <b>.</b> 을 입력하여 어떤 메서드를 사용할 수 있는지 확인해 보면 다양한 중간 연산을 시도해 보는 데 도움된다.
```

2021-05-25 07:05 UTC, wannte requested changes
글의 호흡이 조금 긴 것 같은게 걸리긴 하네요..
많은 설명을 해주고 싶은 마음이 느껴져서.. 그래도 좋은 글 써주셔서 감사합니다!

2021-05-25 07:05 UTC, wannte commented on src/content/post/2021-05-23-stream-api-basic.md
> +}
collection을 이용해서 구현했을 때랑, stream으로 이용했을 때 코드의 차이를 보여줬으면 좋을 것 같아요!

collection으로 구현하게 되었을 때 코드가 길어질 수 도 있는데, 중간연산을 isAdult만을 사용하는 것도 좋을 것 같아요.

메소드 명도, findAultMember로 의미를 가지게 수정하는 것도 좋을 것같아요

2021-05-25 07:09 UTC, GwangYeol-Im requested changes
글 잘 봤습니다 와일더 :) 상세 코멘트 달아드린 부분만 고쳐주시면 좋을 듯 합니다 !

2021-05-29 09:26 UTC, lns13301 commented on src/content/post/2021-05-23-stream-api-basic.md
> +}
해당 부분은 코드의 차이를 나타내기 보다는 StreamAPI 를 이렇게 사용할 수 있다를 알려주기 위한 예시입니다. 해당 예시까지 넣으면 안그래도 긴글이 더 길어질 것 같아요 ㅠㅠ

2021-05-31 12:01 UTC, GwangYeol-Im approved these changes
수정 사항 확인했습니다 와일더! 지식 적인 부분에 대해 피드백을 드릴 수 없어 아쉽네요ㅠ 글 잘 읽었습니다~!

2021-06-08 04:35 UTC, wannte approved these changes
피드백 반영확인했습니다!~ 수고했어요!

2021-06-17 08:34 UTC, da-nyee approved these changes
안녕하세요, 와일더!
리뷰가 늦어져 죄송합니다 😥

피드백 반영한 것 확인했습니다 !
수고하셨습니다 👏👏

2021-06-18 04:14 UTC, kang-hyungu approved these changes
머지 처리할게요. 수고하셨습니다~!

2021-06-18 04:14 UTC, merged