[파노] 타입스크립트 미니멀 스타트 - 1
woowacourse/javable pull request #371
Opened 2021-05-26 11:41 UTC by jho2301

감사합니다 ㅎㅎ..

2021-06-07 03:53 UTC, 0imbean0 approved these changes
파노 늦어서 죄송합니다.
경험을 중심으로 쓴 글이라 어렵지 않게 읽혔던 것 같아요.
잘 읽었습니다. 다음 편도 기대되네요. 😀

2021-06-12 11:57 UTC, xlffm3 commented
안녕하세요 파노 리뷰가 늦었네요!!
js를 쓰면서 가장 아쉬웠던점 중 하나가 컴파일타임에 제 실수를 ide가 체크하지 못한다는 점이었는데요.
타입스크립트를 통해 이런 문제들을 어느정도 해소할 수 있을것같네요 :) 재미있게 읽었습니다!
시리즈물이니 다음 편도 기대할게요

2021-06-12 11:57 UTC, xlffm3 approved these changes

2021-06-16 05:06 UTC, devJang requested changes
안녕하세요 파노

타입스크립트를 공부하고 또 전파하는 모습이 참 멋집니다.

몇가지 의견을 담아볼게요

- 시리즈 아티클이라면 부제를 만드는건 어떨까요? (벨로그 시리즈와 같은)
- 인트로 있는 경험과 예가 더 자세하게 풀어지면 매우 재미있을 듯 해요
- 타이핑 예제는 워낙 흔한 아티클과 튜토리얼이 많아 잘 작성해주셨지만 흥미가 절감되네요ㅠㅠ

마지막으로 튜토리얼 향 아티클로 갈 것인가 좀 애매한 상황인데요.
이러한 정체성을 명확하게 가져가는게 어떨까 제안해봅니다~

2021-06-16 12:35 UTC, jho2301 commented on src/content/post/2021-05-23-typescript-minimal-start.md
> +## 1. 타입 넣기
예시코드를 자꾸 수정하게 되니까 너무 불편하더라구요 ㅋㅋ;;
후킹하는 느낌으로 앞에만 이쁘게 이미지를 삽입한다고 하면, 너무 변명일까요

2021-06-19 09:11 UTC, devJang commented on src/content/post/2021-05-23-typescript-minimal-start.md
> +<<<<<<< HEAD
충돌 있는 것 같은데 괜찮아요?

2021-06-19 09:12 UTC, devJang commented on src/content/post/2021-05-23-typescript-minimal-start.md
> +<<<<<<< HEAD
이것도 충돌?

2021-06-19 10:04 UTC, jho2301 commented on src/content/post/2021-05-23-typescript-minimal-start.md
> +<<<<<<< HEAD
저장이 안됐네요..

2021-06-19 12:01 UTC, merged